version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/data/postgres
    ports:
      - 54320:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
    - .env

volumes:
  postgres-data:
